# Contains the URI of the downstream REST API used to retrieve astronomical body
# data. The value can be accessed by a class like this:
#
# @Value("${application.astronomical.data.bodies-url}")
application:
  astronomical:
    data:
      base-url: https://api.le-systeme-solaire.net/rest
      bodies-url: ${application.astronomical.data.base-url}/bodies